version: 2.0.{build}

environment:
   matrix:
      # Visual Studio 2015https://github.com/IlyaFinkelshteyn/Glyphfriend/pulls
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
        SRC_FOLDER: src/Glyphfriend.VS2015
      # Visual Studio 2017
      - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017 RC
        SRC_FOLDER: src/Glyphfriend.VS2017

configuration:
   - Release

install:
   - ps: (new-object Net.WebClient).DownloadString("https://raw.github.com/madskristensen/ExtensionScripts/master/AppVeyor/vsix.ps1") | iex
   - powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.ps1'))}"

before_build:   
   - nuget restore
    #%SRC_FOLDER%

build_script:
   - msbuild /p:configuration=Release /p:DeployExtension=false /p:ZipPackageCompressionLevel=normal /v:m

after_test:
   - ps: Vsix-PushArtifacts | Vsix-PublishToGallery

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
